### ISSUE TITLE
token 没有验证码登录不了

### ISSUE THREAD

**Issue by tjwangws** [ymc023/pushell#2]
您好  环境已经搭建完了，但是不知道token验证码，登录不了，怎么获取验证码，求大神指点？？？

**Comment by ymc023** [comment]
你好，代码内置的key是：NFP7DMPDPEFK6I6S  ,你可以在手机上使用 freeotp软件，添加这个key,生成的token就可以正常验证了，二次认证路径pushell/two_auth.py  你可以自行修改
class TwoAuth():
    def __init__ (self,secret='NFP7DMPDPEFK6I6S'):
        self.secret = 'NFP7DMPDPEFK6I6S'
        self.totp = pyotp.TOTP(secret)
    def gen_token(self):
